.github/workflows/call_code_review_infra.yaml
.github/workflows/call_release_infra.yaml
.github/workflows/pr_repository.yaml
.github/workflows/release_repository.yaml
infra/repository/.terraform.lock.hcl
infra/repository/README.md
infra/repository/data.tf
infra/repository/github_branch_rules.tf
infra/repository/github_environment_cd.tf
infra/repository/github_environment_ci.tf
infra/repository/github_repo_secrets.tf
infra/repository/locals.tf
infra/repository/main.tf
infra/repository/outputs.tf

Define this GitHub repository settings through a Terraform configuration
IaC is better than UI
---

[EC-222] Add GitHub repository settings in a Terraform configuration

---

.github/workflows/pr_infra.yaml
infra/prod/_modules/cosmos/cosmos_container_client.tf
infra/prod/_modules/cosmos/cosmos_container_grant.tf
infra/prod/_modules/cosmos/cosmos_container_interaction.tf
infra/prod/_modules/cosmos/cosmos_container_session.tf

EC-224] Rename Cosmos DB container names

---

infra/prod/_modules/networking/data.tf
infra/prod/_modules/networking/locals.tf
infra/prod/_modules/networking/main.tf
infra/prod/_modules/networking/outputs.tf
infra/prod/_modules/networking/subnet_fims.tf
infra/prod/_modules/networking/variables.tf
infra/prod/westeurope/.terraform.lock.hcl
infra/prod/westeurope/README.md
infra/prod/westeurope/networking.tf

Add networking module:
- subnet
- nat association
Bringing here FIMS resources
---

[EC-226] Add FIMS networking module

---

.vscode/extensions.json

Add Terraform extensions
Add EditorConfig support extention
Add GitHub extensions
Essential extensions to work within `infra` folder
---

[EC-227] Add vs code recommended extensions

---

infra/prod/westeurope/networking.tf

Add why and link to vnet common definition
Documentating things
---

[EC-226] Add inline doc to FIMS cidr definition

---

README.md

Add fundamental documentation for `infra` workspace
Adding some doc while going forward with the project
---

[EC-228] Add fundamental documentation for infra

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.vscode/extensions.json
.vscode/settings.json
README.md

Setup configuration for working on this project through [Development Containers](https://containers.dev/)
Added support to:
* `node` with `corepack`
* `yarn 4`
* `terraform`, `az cli`
* `pre-commit`
* `plantuml` (`java` + `graphviz`)
**ACHTUNG** ⚠️ This is just an initial implementation, we plan to expand it (with the aim of making it usable by other teams) as this product is developed.

Setup devcontainer

---

.github/workflows/release_infra.yaml
infra/identity/_modules/managed_identities/locals.tf

Add PagoPA IaC Reader role to GitHub CI identity
Update release workflow path trigger
Complete successfully the release workflow
---

[EC-231] Add role to GitHub CI identity

---

.github/workflows/pr_github_runner.yaml
.github/workflows/release_github_runner.yaml
infra/github-runner/prod/westeurope/.terraform.lock.hcl
infra/github-runner/prod/westeurope/README.md
infra/github-runner/prod/westeurope/container_app_job.tf
infra/github-runner/prod/westeurope/locals.tf
infra/github-runner/prod/westeurope/main.tf
infra/github-runner/prod/westeurope/outputs.tf

Add self-hosted runner for this repository
Some infra actions must be performed within the VNET
---

[EC-270] Add GitHub self-hosted runner

---

infra/repository/README.md
infra/repository/github_repository.tf

1. track `pagopa/io-fims` repository settings on terraform

chore(repo): add repository setting

---

.github/labeler.yml

* [Add user label automation](https://github.com/pagopa/io-fims/commit/121fd83ac795bedd786fefb2eb1ec681cae42e30);
* [Add relying-party label automation](https://github.com/pagopa/io-fims/commit/6930d96ea977ed339ed1a924bb3a59583e5844d4);
* [Add openid-provider label automation](https://github.com/pagopa/io-fims/commit/9ff03fc33d32a23d67e5d92ca93e04e42dcf88f1);
* [Add documentation label automation](https://github.com/pagopa/io-fims/commit/df47bc9319cf222b2f8adc71691f8292e0fd19e2).
We want to facilitate the review process.
---

chore(automation): Adds more automation on labels

---

.github/workflows/code-review.yaml
infra/repository/README.md
infra/repository/data.tf
infra/repository/locals.tf

1. add `CODECOV_TOKEN` as repo secret (read from `io-p-fims-kv`)
2. update `codecov/codecov-action` to use `CODECOV_TOKEN` as `token` input
3. (_refactor_) removed `project` and `product` locals from `infra/repository` that are redundant. It's unlikely that they will change in future.
https://about.codecov.io/ will allow us to monitor our coverage across the workspaces, this change complete the configuration needed.
---

ci(code-review): configure codecov

---

CODEOWNERS

Add engineering-team-cloud-eng as CODEOWNERS of infra and github paths
---

Add engineering-team-cloud-eng as CODEOWNERS

---

apps/op-app/openapi.yaml

1. Edit `op-app`'s `openapi.yaml` to document all the HTTP errors returned and their schemas
The mobile client needs these errors to better handle them

Document op-app http errors

---

apps/user-func/src/adapters/cosmos/access-history-page.ts

1. encode `continuationToken` in `base64url`, in order to be used as query parameter without compatibility issues (it may contain `?` characters, that break urls)
2. set max item count of `15` (instead of `100`, the default one)
3. order access history by timestamp desc

fix(user-func): access history pagination

---

apps/rp-example-app/src/app.ts

1. increase rate limit from `5` to `100` request
`rp-example-app` is an example RP used for testing and demoing, the previous limit was too strict for testing purpose

fix(rp-example-app): increase rate limit

---

apps/op-app/src/adapters/oidc/provider.ts

Enforce validation of custom clientMetadata properties, like `redirect_display_names` to block invalid requests at the start of an Authentication Request
Resolves: IOCOM-2094

Add validator for custom clientMetadata

---

.github/labeler.yml
.github/workflows/labeler.yaml

Upate labeler gha

---

.github/workflows/infra-release.yaml
.github/workflows/infra-review.yaml
.pre-commit-config.yaml
infra/bootstrapper/prod/README.md
infra/bootstrapper/prod/data.tf
infra/bootstrapper/prod/locals.tf
infra/bootstrapper/prod/main.tf
infra/resources/_modules/key_vaults/data.tf
infra/resources/_modules/key_vaults/variables.tf
infra/resources/_modules/key_vaults_itn/data.tf
infra/resources/prod/.terraform.lock.hcl
infra/resources/prod/README.md
infra/resources/prod/key_vaults.tf
infra/resources/prod/tfmodules.lock.json

Set correct infra environments in terraform plan/apply CICD workflows

---

apps/op-func/src/func.ts
packages/io-fims-common/package.json
packages/io-fims-common/src/adapters/storage-blob/health.ts
yarn.lock

Add health check on storage blobs in op-func
Remove unused cosmosdb references in op-func

Add health check on storage blobs in op-func

---

apps/op-func/local.settings.json.example
apps/op-func/package.json
apps/op-func/src/adapters/config.ts
apps/op-func/src/adapters/env.ts
apps/op-func/src/func.ts
apps/op-func/src/infra/storage/audit-event.ts
apps/op-func/src/infra/storage/config.ts
infra/resources/_modules/web_apps_itn/data.tf
infra/resources/_modules/web_apps_itn/op_func.tf
infra/resources/_modules/web_apps_itn/variables.tf
infra/resources/prod/web_apps.tf
package.json
yarn.lock

Removes @pagopa/azure-storage-migration-kit
Removes audit fallback container references

Remove migration toolkit and audit fallback
